namespace: minio

image:
  repository: quay.io/minio/minio
  tag: RELEASE.2025-04-22T22-12-26Z
  pullPolicy: IfNotPresent

mcImage:
  repository: quay.io/minio/mc
  tag: RELEASE.2025-04-16T18-13-26Z
  pullPolicy: IfNotPresent

auth:
  rootUser: adminuser
  rootPassword: adminuser

service:
  port: 9000

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Initial buckets, 1 line/bucket
bucket: minio

