apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "minio.fullname" . }}-bucket-job-nonroot-v2
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: {{ include "minio.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:nonroot-v2
subjects:
  - kind: ServiceAccount
    name: {{ include "minio.fullname" . }}-bucket-job
    namespace: {{ .Values.namespace }}
