apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minio.fullname" . }}-bucket-job
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: {{ include "minio.name" . }}
