apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: {{ include "minio.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "minio.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "minio.name" . }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.auth.rootUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.auth.rootPassword | quote }}
          ports:
            - name: api
              containerPort: {{ .Values.service.port }}
            - name: console
              containerPort: 9001
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "minio.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
