apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-np
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ include "minio.name" . }}
  ports:
    - port: 9001
      name: 9001-http